version: '3.1'

services:
  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   container_name: mongodb
  #   environment:
  #       MONGO_INITDB_DATABASE: product

  demo-springboot-app:
    build: .
    container_name: "demo-springboot-app"
    restart: always
    ports:
      - "9090:8080"
    # depends_on:
    #   - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://aribera:eHwHsJelvXlkgdk4@cluster0.uhbqazz.mongodb.net/db01?retryWrites=true&w=majority&appName=Cluster0

volumes:
  mongo-data: